---
kind: pipeline
name: linux-amd64-qBittorrent

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    auto_tag: true
    build_args_from_env:
    - QBITTORRENT_VERSION
    - FILEBOT_VERSION
    - S6_OVERLAY_VERSION
    repo: devster31/qbittorrent-filebot
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

...