---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

server:
  image: docker-18-04
  size: s-1vcpu-2gb
  region: lon1

platform:
  os: linux
  arch: amd64

steps:
# - name: build
#   image: plugins/docker
#   settings:
#     auto_tag: true
#     build_args_from_env:
#     - QBITTORRENT_VERSION
#     - FILEBOT_VERSION
#     - S6_OVERLAY_VERSION
#     repo: devster31/qbittorrent-filebot
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password

- name: build
  commands:
  - echo $QBITTORRENT_VERSION $FILEBOT_VERSION $S6_OVERLAY_VERSION
  - echo $$QBITTORRENT_VERSION $$FILEBOT_VERSION $$S6_OVERLAY_VERSION
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build --build-arg QBITTORRENT_VERSION=$QBITTORRENT_VERSION --build-arg FILEBOT_VERSION=$FILEBOT_VERSION --build-arg S6_OVERLAY_VERSION=$S6_OVERLAY_VERSION --tag devster31/qbittorrent-filebot .
  - docker push devster31/qbittorrent-filebot:$REV
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password

...