---
name: docker build
on:
  push:
    paths:
      - '!README.md'
      - 'LICENSE'
  repository_dispatch: ~
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1
        with:
          docker_version: 19.03
          docker_channel: stable

      - name: Version check
        shell: bash
        run: |
          # start of script
          function get_token() {
            local image=$1
            curl -sS \
              "https://auth.docker.io/token?scope=repository:$image:pull&service=registry.docker.io" \
              | jq -r '.token'
          }

          function get_digest() {
            local image=$1
            local tag=$2
            local token=$3
            curl -sSL \
              --header "Accept: application/vnd.docker.distribution.manifest.v2+json" \
              --header "Authorization: Bearer $token" \
              "https://registry-1.docker.io/v2/$image/manifests/$tag" \
              | jq -r '.config.digest'
          }

          function get_image_configuration() {
            local image=$1
            local token=$2
            local digest=$3
            curl -sSL --header "Authorization: Bearer $token" \
              "https://registry-1.docker.io/v2/$image/blobs/$digest" \
              | jq -r '.container_config'
          }

          function get_image_info {
            local image="devster31/qbittorrent-filebot"
            local token
            token=$(get_token $image)
            local digest
            digest=$(get_digest "${image}" "${tag:-latest}" "${token}")
            get_image_configuration "${image}" "${token}" "${digest}"
          }

          EXT_S6_VER=$(get_image_info | jq -r '.Labels."org.opencontainers.image.s6-overlay.version"')
          EXT_FB_VER=$(get_image_info | jq -r '.Labels."org.opencontainers.image.filebot.version"')
          EXT_QB_VER=$(get_image_info | jq -r '.Labels."org.opencontainers.image.qbittorrent.version"')

          S6_URL=https://api.github.com/repos/just-containers/s6-overlay/releases/latest
          RESP=$(curl -Ls -w "%{http_code}" -o /dev/null "${S6_URL}")
          if [ "${RESP}" == 200 ]; then
            CUR_S6_VER=$(curl -sS "${S6_URL}" | jq --raw-output '.tag_name')
          else
            echo "::error ::Unable to get the URL:${S6_URL}"
            exit 1
          fi

          FB_DEB_URL="https://get.filebot.net/deb/dists/stable/main/binary-amd64/Packages"
          RESP=$(curl -Ls -w "%{http_code}" -o /dev/null "${FB_DEB_URL}")
          if [ "${RESP}" == 200 ]; then
            CUR_FB_VER=$(curl -sSX GET "${FB_DEB_URL}" | awk -F ': ' '/Version/{print $2;exit}')
          else
            echo "::error ::Unable to get the URL:${QB_DEB_URL}"
            exit 1
          fi

          QB_DEB_URL=http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu/dists/bionic/main/binary-amd64/Packages.gz
          QB_PKG=qbittorrent-nox
          RESP=$(curl -Ls -w "%{http_code}" -o /dev/null "${QB_DEB_URL}")
          if [ "${RESP}" == 200 ]; then
            CUR_QB_VER=$(curl -sSX GET "${QB_DEB_URL}" | gunzip -c | \
              awk -F ': ' "/Package: ${QB_PKG}/,/Version/{ y = \$0 } END { split(y, a) ; print a[2] }")
          else
            echo "::error ::Unable to get the URL:${QB_DEB_URL}"
            exit 1
          fi

          SHORT_TAG=$(echo "${CUR_QB_VER}" | awk -F '[:~]' '{ print $2 }')
          FULL_TAG=qbt-v$(echo "${CUR_QB_VER}" | awk -F '[:~]' '{ print $2 }')~fb-v"${CUR_FB_VER}"

          if [ "${CUR_QB_VER}" != "${EXT_QB_VER}" ] || \
             [ "${CUR_FB_VER}" != "${EXT_FB_VER}" ] || \
             [ "${CUR_S6_VER//v}" != "${EXT_S6_VER}" ]; then
            RUN_BUILD=yes
          else
            RUN_BUILD=no
          fi

          echo "::set-output name=short_tag::${SHORT_TAG}"
          echo "::set-output name=full_tag::${FULL_TAG}"
          echo "::set-output name=s6_version::${CUR_S6_VER//v}"
          echo "::set-output name=fb_version::${CUR_FB_VER}"
          echo "::set-output name=qb_version::${CUR_QB_VER}"
          echo "::set-output name=trigger::${RUN_BUILD}"
        id: version_check

      - name: Build
        if: success() && steps.version_check.outputs.trigger == "yes"
        run: |
          echo ${{ secrets.docker_hub_password }} | docker login --username ${{ secrets.docker_hub_username }} --password-stdin
          docker build . \
            --build-arg SHORT_TAG_VER="${{ steps.version_check.outputs.short_tag }}" \
            --build-arg FULL_TAG_VER="${{ steps.version_check.outputs.full_tag }}" \
            --build-arg FILEBOT_VER="${{ steps.version_check.outputs.fb_version }}" \
            --build-arg QBITTORRENT_VER="${{ steps.version_check.outputs.qb_version }}" \
            --build-arg S6_OVERLAY_VER="${{ steps.version_check.outputs.s6_version }}" \
            --tag devster31/qbittorrent-filebot:latest \
            --tag devster31/qbittorrent-filebot:"${{ steps.version_check.outputs.short_tag }}" \
            --tag devster31/qbittorrent-filebot:"${{ steps.version_check.outputs.full_tag }}"
          docker push devster31/qbittorrent-filebot
...
