#!/command/with-contenv bash

set -o xtrace

# make our folders
mkdir -p \
	/config/qBittorrent \
	/config/data \
	/filebot

# copy config
[[ ! -e /config/qBittorrent/qBittorrent.conf ]] && \
	cp /defaults/qBittorrent.conf /config/qBittorrent/qBittorrent.conf

# permissions
chown -R abc:abc \
	/config \
	/filebot
